# Generated by Django 4.2.5 on 2023-09-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaign', '0002_alter_campaign_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=75, unique=True),
        ),
    ]
